version: '3.7'

networks:
  dbnet:
    external: true
    name: dbnet

services:
  main-app:
    image: veekz/sfc-prj-main-app-preproduction:latest
    container_name: sfc-prj-main-app
    ports:
      - "5000:3000"
    links:
      - kafka
    extra_hosts:
      - kafka:host-gateway
    environment:
      DB_HOST: host.docker.internal
      FASTIFY_ADDR: "0.0.0.0"
      FASTIFY_PORT: 3000
      APP_KAFKA_BOOTSTRAP_SERVER: host.docker.internal:9092
      APP_KAFKA_TOPIC: topic-main-app
      KAFKA_APP_NAME: sfc-prj-main-app
      KAFKA_GROUP_NAME: sfc-prj
      KAFKA_USAGE: true
    networks:
      - dbnet
  ms1:
    image: veekz/sfc-prj-ms1-preproduction:latest
    container_name: sfc-prj-ms1
    ports:
      - "5001:3000"
    links:
      - kafka
    extra_hosts:
      - kafka:host-gateway
    environment:
      DB_HOST: host.docker.internal
      FASTIFY_ADDR: "0.0.0.0"
      FASTIFY_PORT: 3000
      APP_KAFKA_BOOTSTRAP_SERVER: host.docker.internal:9092
      APP_KAFKA_TOPIC: topic-main-app
      KAFKA_APP_NAME: sfc-prj-ms1
      KAFKA_GROUP_NAME: sfc-prj
      KAFKA_USAGE: true
    networks:
      - dbnet
  ms2:
    image: veekz/sfc-prj-ms2-preproduction:latest
    container_name: sfc-prj-ms2
    ports:
      - "5002:3000"
    links:
      - kafka
    extra_hosts:
      - kafka:host-gateway
    environment:
      DB_HOST: host.docker.internal
      FASTIFY_ADDR: "0.0.0.0"
      FASTIFY_PORT: 3000
      APP_KAFKA_BOOTSTRAP_SERVER: host.docker.internal:9092
      APP_KAFKA_TOPIC: topic-main-app
      KAFKA_APP_NAME: sfc-prj-ms2
      KAFKA_GROUP_NAME: sfc-prj
      KAFKA_USAGE: true
    networks:
      - dbnet

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: tutorial
      POSTGRES_DB: iam
      POSTGRES_PASSWORD: privatepassword
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: privatepassword
    ports:
      - "8000:80"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_QUORUM_LISTEN_ON_ALL_IPS: 'true'
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
      - "9094:9094"
    hostname: kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper
    extra_hosts:
      - kafka:host-gateway
      - host.docker.internal:host-gateway
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "host.docker.internal:2181"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: INTERNAL://:9094,OUTSIDE://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9094,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 1
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    links:
      - kafka
      - zookeeper
    environment:
      KAFKA_CLUSTERS_0_NAME: "kafka"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9094"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "host.docker.internal:2181"