version: '3.7'

networks:
  dbnet:
    external: true
    name: dbnet

services:
  main-app:
    image: veekz/sfc-prj-main-app-preproduction:latest
    container_name: sfc-prj-main-app
    ports:
      - "5000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: host.docker.internal
      FASTIFY_ADDR: "0.0.0.0"
      FASTIFY_PORT: 3000
      APP_KAFKA_BOOTSTRAP_SERVER: kafka:9092
      APP_KAFKA_TOPIC: topic-main-app
      KAFKA_APP_NAME: sfc-kafka-main-app
      KAFKA_GROUP_NAME: sfc-prj
    networks:
      - dbnet
  ms1:
    image: veekz/sfc-prj-ms1-preproduction:latest
    container_name: sfc-prj-ms1
    ports:
      - "5001:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: host.docker.internal
      DB_SYNCHRONIZE: false
      FASTIFY_ADDR: "0.0.0.0"
      FASTIFY_PORT: 3000
      APP_KAFKA_BOOSTRAP_SERVER: kafka:9092
      APP_KAFKA_TOPIC: topic-main-app
      KAFKA_APP_NAME: sfc-kafka-ms1
      KAFKA_GROUP_NAME: sfc-prj
    networks:
      - dbnet
  ms2:
    image: veekz/sfc-prj-ms2-preproduction:latest
    container_name: sfc-prj-ms2
    ports:
      - "5002:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: host.docker.internal
      DB_SYNCHRONIZE: false
      FASTIFY_ADDR: "0.0.0.0"
      FASTIFY_PORT: 3000
      APP_KAFKA_BOOSTRAP_SERVER: kafka:9092
      APP_KAFKA_TOPIC: topic-main-app
      KAFKA_APP_NAME: sfc-kafka-ms2
      KAFKA_GROUP_NAME: sfc-prj
    networks:
      - dbnet

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: tutorial
      POSTGRES_DB: iam
      POSTGRES_PASSWORD: privatepassword
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: privatepassword
    ports:
      - "8000:80"
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092