version: '3.7'

networks:
  dbnet:
    external: true
    name: dbnet

services:
  main-app:
    image: veekz/sfc-prj-main-app-preproduction:latest
    container_name: sfc-prj-main-app
    ports:
      - "5000:5000"
    networks:
      - dbnet
  ms1:
    image: veekz/sfc-prj-ms1-preproduction:latest
    container_name: sfc-prj-ms1
    ports:
      - "5001:5001"
    networks:
      - dbnet
  ms2:
    image: veekz/sfc-prj-ms2-preproduction:latest
    container_name: sfc-prj-ms2
    ports:
      - "5002:5002"
    networks:
      - dbnet

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: tutorial
      POSTGRES_DB: iam
      POSTGRES_PASSWORD: privatepassword
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: privatepassword
    ports:
      - "8000:80"