{
 "title": "Flask prometheus",
 "time": { "from": "2023-02-14T20:13:22.014Z", "to": "2023-02-14T20:58:03.867Z" },
 "panels": [
  {
   "title": "Scraped Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "scrape_samples_scraped", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process CPU seconds total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Garbage Collector Uncollectable Objects",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "python_gc_objects_uncollectable_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage collector total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "python_gc_collections_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory bytes",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 10 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "File system",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 6, "x": 12, "y": 10 },
   "targets": [
    { "expr": "process_max_fds", "legendFormat": "__auto" },
    { "expr": "process_open_fds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Garbage Collector Collected Objects",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Start Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "targets": [
    { "expr": "process_start_time_seconds", "legendFormat": "__auto" }
   ]
  }
 ]
}